# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - JagatAppService

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.11'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Run a one-line script
        run: sudo apt-get update
      
      - name: Run a one-line script
        run: sudo apt install python3-pip
        
      - name: Run a one-line script
        run:  sudo apt update && sudo apt install -y libsm6 libxext6 ffmpeg libfontconfig1 libxrender1 libgl1-mesa-glx
        
      - name: Run a one-line script
        run: pip3 install pytesseract
        
      - name: Run a one-line script
        run: pip3 install -U opencv-python
        
      - name: Run a one-line script
        run: sudo apt-get install tesseract-ocr

      - name: Install dependencies
        run: pip install -r .github/workflows/requirements.txt
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_8193F74990E5431CBBD4E95E494AE81C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_582F6F32AF364BAF90B73862177AA2F8 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A0573EBDFA3448D3A7B3FCFCA311AF6B }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'JagatAppService'
          slot-name: 'Production' 
      
      - name : List file available in this deploy
        run : find / -type f -name "app.py"
      - name : Print current directory
        run : pwd